# Generated by Django 3.2 on 2021-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
