# Generated by Django 3.2 on 2021-05-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210511_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
